import Foundation
import GRDB
import Testing
@testable import MemoryV2

/// Eval for ledger surface `memory.storage.schemaMigrations`
/// (docs/evals/ledger.json, fence core.memory).
///
/// Silent-failure class: one-way data loss on upgrade. `MemoryStorage.migrator`
/// is the only code that reshapes the live store, and nothing opened a v1-era
/// database and proved it reaches the head schema with rows intact — nor that
/// the APPLIED ledger matches the REGISTERED set. A migration that half-applies
/// (GRDB runs each block in its own transaction, and v3/v5/v6/v7 chain several
/// ALTER TABLEs inside one `execute`) leaves `grdb_migrations` stamped and the
/// columns missing; every later read then decodes NULL for lifecycle/epoch/
/// temporal fields and the store merely looks like a store of old, plain facts.
///
/// The envelope asserted here is "registered set == applied set, ADDITIVELY":
/// the upgrade path from a v1-only database must reach the same applied set and
/// the same column surface as a database created fresh, with every seeded row
/// still carrying its content. Exact migration identifiers ARE contractual —
/// they are persisted in the store, and renaming one re-runs or skips a block on
/// every existing install — so they are pinned by name.
@Suite("MemoryV2 schema migration ladder")
struct SchemaMigrationLadderTests {

    // MARK: - fixture

    private func makeTempRoot(_ label: String) throws -> URL {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("memv2-migladder-\(label)-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        return root
    }

    /// The v1_initial schema, transcribed from `MemoryV2+Storage.swift`
    /// `migrator` → `registerMigration("v1_initial")`. Deliberately hand-written
    /// rather than produced by the migrator: the point of the eval is to replay
    /// a store shaped by the OLD code, and a fixture generated by today's
    /// migrator could never catch a v1 block that silently changed shape.
    private static let v1Schema = """
        CREATE TABLE memories (
          id TEXT PRIMARY KEY,
          content TEXT NOT NULL,
          persona_id TEXT NOT NULL DEFAULT 'NativeAgent',
          source TEXT,
          confidence REAL DEFAULT 1.0,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL,
          embedding BLOB,
          status TEXT NOT NULL DEFAULT 'active',
          metadata_json TEXT
        );
        CREATE INDEX idx_memories_persona ON memories(persona_id, status);
        CREATE INDEX idx_memories_created ON memories(created_at);
        CREATE INDEX idx_memories_source ON memories(source);

        CREATE TABLE proposals (
          id TEXT PRIMARY KEY,
          content TEXT NOT NULL,
          persona_id TEXT NOT NULL DEFAULT 'NativeAgent',
          source TEXT,
          staged_at TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'pending',
          resolved_at TEXT,
          rejection_reason TEXT,
          embedding BLOB,
          metadata_json TEXT
        );
        CREATE INDEX idx_proposals_status ON proposals(status, staged_at);

        CREATE TABLE tombstones (
          content_hash TEXT PRIMARY KEY,
          content TEXT NOT NULL,
          rejected_at TEXT NOT NULL,
          reason TEXT
        );
        CREATE INDEX idx_tombstones_rejected ON tombstones(rejected_at);
        """

    /// Every identifier registered on `MemoryStorage.migrator`, in order. These
    /// strings are persisted in `grdb_migrations` on every install; the set is
    /// the contract.
    private static let registeredIdentifiers = [
        "v1_initial",
        "v2_knowledge_graph",
        "v3_recall_counters",
        "v4_tombstone_embeddings",
        "v5_memory_lifecycle",
        "v6_embedding_epochs",
        "v7_temporal_evidence",
    ]

    /// Write a memory.sqlite that looks like a v1-era install: v1 tables, rows,
    /// and a `grdb_migrations` ledger holding ONLY the identifiers in `stamped`.
    @discardableResult
    private func seedLegacyStore(
        at root: URL,
        stamped: [String] = ["v1_initial"]
    ) throws -> URL {
        let dir = root.appendingPathComponent("memory", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let path = dir.appendingPathComponent("memory.sqlite")
        let queue = try DatabaseQueue(path: path.path)
        try queue.write { db in
            try db.execute(sql: Self.v1Schema)
            try db.execute(sql: "CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY);")
            for identifier in stamped {
                try db.execute(
                    sql: "INSERT INTO grdb_migrations (identifier) VALUES (?)",
                    arguments: [identifier]
                )
            }
            try db.execute(sql: """
                INSERT INTO memories (id, content, persona_id, source, confidence, created_at, updated_at, status, metadata_json)
                VALUES
                  ('legacy-1', 'User reviews every worker diff before it ships', 'Agent', 'chat', 0.9,
                   '2026-05-01T00:00:00Z', '2026-05-01T00:00:00Z', 'active', '{"kind":"preference"}'),
                  ('legacy-2', 'the memory store lives under <dataRoot>/memory', 'Agent', 'migration', 1.0,
                   '2026-05-02T00:00:00Z', '2026-05-02T00:00:00Z', 'active', NULL);
                INSERT INTO proposals (id, content, persona_id, staged_at, status)
                VALUES ('legacy-p1', 'a staged legacy claim', 'Agent', '2026-05-03T00:00:00Z', 'pending');
                INSERT INTO tombstones (content_hash, content, rejected_at, reason)
                VALUES ('deadbeef', 'a rejected legacy claim', '2026-05-04T00:00:00Z', 'rejected');
            """)
        }
        // Drop the connection before MemoryStorage opens its own pool.
        try queue.close()
        return path
    }

    // MARK: - readers

    private func appliedIdentifiers(at path: URL) throws -> [String] {
        let queue = try DatabaseQueue(path: path.path)
        defer { try? queue.close() }
        return try queue.read { db in
            try String.fetchAll(db, sql: "SELECT identifier FROM grdb_migrations ORDER BY rowid")
        }
    }

    private func columns(at path: URL, table: String) throws -> Set<String> {
        let queue = try DatabaseQueue(path: path.path)
        defer { try? queue.close() }
        return try queue.read { db in
            Set(try Row.fetchAll(db, sql: "PRAGMA table_info(\(table))").map { $0["name"] as String })
        }
    }

    private func tables(at path: URL) throws -> Set<String> {
        let queue = try DatabaseQueue(path: path.path)
        defer { try? queue.close() }
        return try queue.read { db in
            Set(try String.fetchAll(
                db,
                sql: "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
            ))
        }
    }

    // MARK: - the ladder

    @Test("a v1-era store reaches the head schema with every seeded row intact")
    func v1StoreUpgradesAdditively() async throws {
        let root = try makeTempRoot("upgrade")
        defer { try? FileManager.default.removeItem(at: root) }
        let path = try seedLegacyStore(at: root)

        #expect(try appliedIdentifiers(at: path) == ["v1_initial"])

        let storage = try MemoryStorage(dataRoot: root)

        // 1. Applied set == registered set. Not "at least" — an extra applied
        //    identifier means a block ran that this build does not register.
        #expect(try appliedIdentifiers(at: path) == Self.registeredIdentifiers)

        // 2. Every column each later migration adds is actually present. This
        //    is the half-apply detector: GRDB stamps the ledger per block, so a
        //    block that dies mid-`execute` leaves the stamp and drops columns.
        let memoryColumns = try columns(at: path, table: "memories")
        for column in ["use_count", "last_used_at", "lifecycle", "embedding_epoch",
                       "valid_from", "valid_to", "observed_at", "evidence_json"] {
            #expect(memoryColumns.contains(column), "memories.\(column) missing after upgrade")
        }
        #expect(try columns(at: path, table: "proposals").contains("embedding_epoch"))
        let tombstoneColumns = try columns(at: path, table: "tombstones")
        #expect(tombstoneColumns.contains("embedding"))
        #expect(tombstoneColumns.contains("embedding_epoch"))

        let tableNames = try tables(at: path)
        for table in ["kg_entities", "kg_relationships",
                      "memory_embedding_state", "memory_embedding_previous"] {
            #expect(tableNames.contains(table), "\(table) missing after upgrade")
        }

        // 3. The rows survive, with their content, through the whole ladder —
        //    and the additive columns land on the DEFAULTS the migrations
        //    promise (legacy rows stay confirmed, are never epoch-stamped, and
        //    are never assigned invented temporal validity).
        let memories = try await storage.listMemories(persona: nil, status: nil, limit: nil)
        #expect(Set(memories.map(\.id)) == ["legacy-1", "legacy-2"])
        let first = try #require(memories.first { $0.id == "legacy-1" })
        #expect(first.content == "User reviews every worker diff before it ships")
        #expect(first.personaId == "Agent")
        #expect(first.lifecycle == MemoryLifecycle.confirmed)
        #expect(first.useCount == 0)
        #expect(first.lastUsedAt == nil)
        #expect(first.embeddingEpoch == nil)
        #expect(first.validFrom == nil)
        #expect(first.validTo == nil)
        #expect(first.observedAt == nil)
        #expect(first.evidence == nil)

        #expect(try await storage.listProposals(status: "pending").map(\.id) == ["legacy-p1"])

        // 4. The v6 singleton exists and starts empty — a store whose epoch row
        //    is missing makes every later epoch read decode as "no active
        //    epoch" and silently disables epoch protection.
        let epochState = try await storage.embeddingEpochState()
        #expect(epochState.activeEpoch == nil)
        #expect(epochState.rollbackAvailable == false)
    }

    @Test("the upgraded schema is identical to a freshly created one")
    func upgradePathMatchesFreshCreate() throws {
        let upgradedRoot = try makeTempRoot("upgraded")
        let freshRoot = try makeTempRoot("fresh")
        defer {
            try? FileManager.default.removeItem(at: upgradedRoot)
            try? FileManager.default.removeItem(at: freshRoot)
        }
        let upgradedPath = try seedLegacyStore(at: upgradedRoot)
        _ = try MemoryStorage(dataRoot: upgradedRoot)
        _ = try MemoryStorage(dataRoot: freshRoot)
        let freshPath = freshRoot
            .appendingPathComponent("memory", isDirectory: true)
            .appendingPathComponent("memory.sqlite")

        #expect(try appliedIdentifiers(at: upgradedPath) == appliedIdentifiers(at: freshPath))
        #expect(try tables(at: upgradedPath) == tables(at: freshPath))
        for table in ["memories", "proposals", "tombstones",
                      "kg_entities", "kg_relationships",
                      "memory_embedding_state", "memory_embedding_previous"] {
            #expect(
                try columns(at: upgradedPath, table: table) == columns(at: freshPath, table: table),
                "column surface diverges on \(table) between the upgrade path and a fresh create"
            )
        }
    }

    /// Negative control — the half-applied store the silent-failure mode
    /// describes: the ledger claims blocks ran that never reshaped the schema.
    /// Opening such a store must FAIL LOUDLY rather than come up green and then
    /// decode NULL for every lifecycle / epoch / temporal field.
    ///
    /// The guard that catches it is `requireSemanticIntegrity`, which runs on
    /// every open and touches columns from the LATEST migrations — so the error
    /// must name the missing schema object, not merely be "some error" (a future
    /// open path that threw for an unrelated reason would otherwise launder this
    /// control into a vacuous pass). Both shapes are exercised: a fully-stamped
    /// ledger over a v1 schema, and a partially-stamped one, which fails on the
    /// missing v2 tables.
    @Test("a store whose migration ledger outruns its schema refuses to open")
    func stampedButUnmigratedStoreFailsLoud() throws {
        func expectLoudSchemaFailure(stamped: [String], label: String) throws {
            let root = try makeTempRoot(label)
            defer { try? FileManager.default.removeItem(at: root) }
            try seedLegacyStore(at: root, stamped: stamped)
            do {
                _ = try MemoryStorage(dataRoot: root)
                Issue.record("half-applied store (\(label)) opened green instead of failing loud")
            } catch {
                let text = "\(error)"
                #expect(
                    text.contains("no such column") || text.contains("no such table"),
                    "expected a missing-schema-object error for \(label), got: \(text)"
                )
            }
        }

        try expectLoudSchemaFailure(stamped: Self.registeredIdentifiers, label: "halfapplied-all")
        try expectLoudSchemaFailure(
            stamped: Array(Self.registeredIdentifiers.prefix(5)),
            label: "halfapplied-v5"
        )
    }
}
