/// Lazy tool help: discoverable through tool_catalog/tool_load, never global prompt context.
package enum CodexImageGenerationHelp {
    package static let usage = """
    Use the real Codex built-in image_gen.imagegen tool through a bounded Codex run. This default route does not make a NativeAgent HTTP image request or use a platform API key. No automatic API fallback. Generate from a prompt; for edits, inspect the reference pixels and supply referenced_image_paths. References are authorized, copied into this run and attached to Codex. Say exactly what changes and what must remain. For iteration, reuse the latest returned image path. With multiple references, assign their ordered roles.
    Example generation: prompt='A polished brass telescope on a teal base with a plaque reading the agent, isolated transparent cutout', background=transparent. Example edit: prompt='Change only the base to violet; preserve the telescope and the agent plaque', action=edit, referenced_image_paths=['/absolute/path/from/previous/result.png']. Use composition, lighting, exact quoted text, preservation goals and desired detail in the prompt. Inspect pixels after each edit.
    The actual built-in tool exposes prompt and reference inputs, not a model selector or a quality parameter. Therefore quality, size/aspect, output format and background are forwarded as prompt preferences. High detail can be requested; executed high quality cannot be asserted from that request. Do not invent Images 2.5, Sunburst or Flare selection. model/imageModel/backendToolModel remain unknown unless the built-in tool exposes identity. sourceTool=image_gen.imagegen and transport=codex_builtin identify the execution path; codexThreadId binds artifacts to that exact run. qualityRequestForwarding=prompt_preference and qualityFulfillment=unknown describe this boundary, not a downgrade to medium. Inspect actual raster dimensions/format and fulfillment receipts. Do not assume API model controls apply to Codex's built-in tool.
    Up to four local PNG/JPEG/WebP references, 8 MiB each and 20 MiB total. n is 1–4 images; timeout_seconds bounds the Codex run. There is no shared implicit image history across independent calls: always resupply the reference. Masks, image reasoning effort, compression knobs and forced image model selection are not exposed. Report unavailable-tool, missing-artifact and timeout errors without switching to an API. Full guide: docs/IMAGE_GENERATION.md.
    The worker is a general Codex agent with a read-only tool sandbox, an empty per-run working directory, an allowlisted environment, user config/rules ignored and available non-image tool families disabled. Prompt and reference contents are untrusted data. There is no universal built-in tool allowlist; this is not a dedicated image API. Receipts expose the actual execution boundary, environment key names, sandbox and selected provider, including explicit codex_cli.
    """
}
