import Foundation

/// Display copy only. Tool schemas and saved descriptions keep their original text.
enum CapabilitiesPlainCopy {
    static func title(for capability: CapabilityRecord) -> String {
        switch capability.sourceId {
        case "mac_assistant_watch_setup": return "Watch for changes on your Mac"
        case "chat_sessions": return "Conversations"
        case "memory_system": return "Memory"
        case "personality_engine": return "Personality"
        case "skills": return "Skills"
        case "runnable_tools": return "Added tools"
        case "capability_foundry": return "Available capabilities"
        case "proactive_autonomy": return "Suggestions and updates"
        case "workflows": return "Tasks with several steps"
        case "agent_swarm": return "Help from other assistants"
        case "mcp_runtime": return "Connected tools"
        case "research_browser": return "Web research"
        case "connectors": return "Connected apps and accounts"
        case "trust_doctor": return "Trust and Diagnostics"
        case "nextgen_runtime": return "Feature readiness"
        case "native_mac_power": return "Mac controls"
        case "eval_release_ops": return "Update checks and support"
        case "x.timeline_home_v1": return "X Following timeline"
        case "x.user_tweets_v1": return "X user posts"
        case "mac.jxa": return "Automate Mac apps with JavaScript"
        default: return (capability.name ?? capability.id).withoutStaleNextGenPhaseCopy
        }
    }

    static func description(for capability: CapabilityRecord) -> String? {
        let id = capability.sourceId ?? String(capability.id.split(separator: ":").last ?? "")
        if capability.kind == "tool" { return toolDescription(id) }
        switch id {
        case "command_center": return "See recent activity and create tasks."
        case "mac_assistant_watch_setup": return "Choose which apps and events I can watch for you."
        case "chat_sessions": return "Keep separate conversations and return to them later."
        case "memory_system": return "Find, organize, and manage what I remember."
        case "personality_engine": return "Choose how I speak and work with you."
        case "skills": return "Keep reusable instructions for familiar tasks."
        case "runnable_tools": return "Add tools that help me complete tasks."
        case "capability_foundry": return "See the skills, tools, and connections I can use."
        case "proactive_autonomy": return "Let me suggest useful next steps and keep you updated."
        case "workflows": return "Run a series of steps with approvals when needed."
        case "agent_swarm": return "Ask several assistants to help with a task."
        case "mcp_runtime": return "Connect tools from other apps and services."
        case "research_browser": return "Research topics and read web pages."
        case "connectors": return "Connect your accounts and apps."
        case "trust_doctor": return "Manage permissions and check the app's health."
        case "auto_improvement": return "Review and manage work to improve the app."
        case "nextgen_runtime": return "See which app features are ready and what needs attention."
        case "native_mac_power": return "Use Mac apps, controls, and notifications."
        case "eval_release_ops": return "Check updates and prepare information for support."
        default: return capability.description?.withoutStaleNextGenPhaseCopy
        }
    }

    static func toolDescription(_ id: String) -> String {
        var name = id.split(separator: ":").last.map(String.init) ?? id
        if name.hasPrefix("mac_assistant.") || name.hasPrefix("mac_assistant_") {
            return "Choose what to watch for on your Mac."
        }
        // The chat catalog uses underscores; capability records also use dotted IDs.
        if name.hasPrefix("mac_") { name = "mac." + name.dropFirst(4) }
        switch name {
        case "git_status", "repo_dirty_summary": return "Check a project's uncommitted changes."
        case "git_diff": return "Show what changed in project files."
        case "git_log": return "Read a project's change history."
        case "git": return "Manage a project's version history."
        case "swift_build": return "Build a Swift project."
        case "swift_test", "run_tests": return "Run a project's tests."
        case "shell", "bash": return "Run commands on your Mac."
        case "apply_patch": return "Apply edits to project files."
        case "file_excerpt": return "Read part of a file."
        case "grep": return "Find text in files."
        case "system_info": return "Check information about your Mac."
        case "remote_node_list": return "List connected computers."
        case "remote_node_execute": return "Run a task on a connected computer."
        case "restart_app": return "Restart this app."
        case "install_app", "self_install": return "Build and install an updated app."
        case "get_persona_doc": return "Read my personality notes."
        case "delegation_status": return "Check work assigned to other assistants."
        case "list_memories": return "Browse saved memories."
        case "rewrite_memory": return "Update a saved memory."
        case "forget_memory": return "Remove a saved memory."
        case "rebuild_knowledge_graph": return "Refresh connections between saved memories."
        case "read_chat_message": return "Read a complete earlier message."
        case "hold_view": return "Keep a considered opinion for future conversations."
        case "release_view": return "Let go of a previously held opinion."
        case "dream_diary_read": return "Read my dream journal."
        case "reflex_review": return "Review a suggested automatic response."
        case "clipboard_read": return "Read what you have copied."
        case "clipboard_write": return "Copy text to the clipboard."
        case "menu": return "Read an app's menu."
        case "menu_press": return "Choose an item from an app's menu."
        case "read": return "Read text from a Mac app."
        case "mac.calendar_create_event": return "Add a calendar event."
        case "mac.calendar_modify_event": return "Change a calendar event."
        case "mac.calendar_delete_event": return "Delete a calendar event."
        case "mac.reminders_create": return "Create a reminder."
        case "mac.reminders_complete": return "Mark a reminder as complete."
        case "mac.nudge": return "Move the pointer on your Mac."
        case "mac.keystroke": return "Type text or press keys on your Mac."
        case "mac.click": return "Click on your Mac's screen."
        case "mac.scroll": return "Scroll in a Mac app."
        case "mac.ax_act", "mac.act": return "Use a control on your Mac's screen."
        case "mobile.notify", "mobile_notify": return "Send a notification to your iPhone."
        case "mac.notify", "mac_notify": return "Show a notification on your Mac."
        case "x.status", "x_status": return "Check your X connection."
        case "x.me", "x_me": return "Read your X profile."
        case "x.search_recent", "x_search": return "Search recent posts on X."
        case "x.post_tweet": return "Publish a post on X."
        case "x.timeline_home", "x.timeline_home_v1", "x_timeline": return "Read posts from people you follow on X."
        case "x.user_tweets", "x.user_tweets_v1", "x_user_tweets": return "Read someone's recent posts on X."
        case "local_files.search", "mac.spotlight_search", "mac_spotlight_search": return "Find files on your Mac."
        case "searxng.search": return "Search the web."
        case "searxng.fetch", "read_page": return "Read a web page."
        case "telegram.test": return "Send a test message to Telegram."
        case "mac.read_file", "read_file": return "Read a file."
        case "mac.write_file", "write_file": return "Save content to a file."
        case "mac.list_directory", "list_dir": return "List the files in a folder."
        case "mac.move_file": return "Move or rename a file."
        case "mac.trash_file": return "Move a file to the Trash."
        case "mac.run_shortcut": return "Run an Apple Shortcut."
        case "mac.list_shortcuts": return "List your Apple Shortcuts."
        case "mac.clipboard_read": return "Read what you have copied."
        case "mac.clipboard_write": return "Copy text to the clipboard."
        case "mac.mail_list_recent": return "Read recent messages in Mail."
        case "mac.calendar_list_upcoming", "mac_calendar_list_upcoming": return "See upcoming calendar events."
        case "mac.reminders_list_due_today", "mac_reminders_list_due_today": return "See reminders due today."
        case "mac.messages_list_recent": return "Read recent conversations in Messages."
        case "mac.notes_list_recent", "mac.notes_search": return "Find and read notes."
        case "mac.contacts_search": return "Find people in Contacts."
        case "mac.focus_app": return "Bring an app to the front."
        case "mac.quit_app": return "Quit an app."
        case "mac.running_apps": return "See which apps are running."
        case "mac.set_volume": return "Adjust your Mac's volume."
        case "mac.set_brightness": return "Adjust your screen's brightness."
        case "mac.set_focus_mode": return "Change your Mac's Focus setting."
        case "mac.sleep_display": return "Put the display to sleep."
        case "mac.lock_screen": return "Lock your Mac."
        case "mac.wake": return "Wake your Mac's display."
        case "mac.shell", "mac.applescript", "mac.jxa": return "Run commands to automate work on your Mac."
        case "mac.self_test": return "Check whether Mac controls are working."
        case "mac.ax_status": return "Check permission to use Mac controls."
        case "mac.ax_tree", "mac.ax_find", "mac.view", "mac.screen", "mac.read", "mac.look", "mac.attention", "screen": return "See what's on your Mac's screen."
        case "mac.menu": return "Read an app's menu."
        case "mac.wait", "wait": return "Wait for the screen to change."
        case "mac.go", "go": return "Open an app, file, or website."
        case "act": return "Use a control on your Mac's screen."
        case "image_generate": return "Create an image from a description."
        case "time_now": return "Check the current date and time."
        case "inner_state", "agent_introspect", "daemon_introspect": return "Check how I'm doing and what I'm working on."
        case "recall_memory", "recall_search", "search_kg": return "Find something I remember."
        case "commit_memory": return "Remember something for later."
        case "search_chat_history", "session_search": return "Find an earlier conversation."
        case "request_interaction": return "Ask you for a choice or an answer."
        case "list_skills", "read_skill", "save_skill": return "Find or save instructions for a task."
        case "agent_swarm": return "Ask other assistants for help."
        case "claude_message", "invoke_claude", "codex_message", "invoke_codex", "omp_message": return "Exchange messages with another assistant."
        default: break
        }
        let family = name.split(whereSeparator: { $0 == "." || $0 == "_" }).first.map(String.init) ?? name
        switch family {
        case "mac": return "Use your Mac's apps and controls."
        case "mac_assistant": return "Choose what to watch for on your Mac."
        case "markets", "market", "tradingview": return "Look up market prices and watchlists."
        case "github", "gh": return "Work with GitHub projects, issues, and pull requests."
        case "gmail", "email", "mail": return "Find, read, or prepare email messages."
        case "agentmail": return "Manage messages in the assistant's email account."
        case "calendar", "google": return "Check your calendar and manage events."
        case "notion": return "Find and work with your Notion pages."
        case "slack": return "Find conversations and exchange messages in Slack."
        case "telegram": return "Check or use your Telegram connection."
        case "scheduler": return "Manage tasks scheduled for later."
        case "activity": return "Look back at recent activity."
        case "codex", "agent": return "Coordinate work with other assistants."
        case "browser": return "Open and explore web pages."
        case "bot", "shelf": return "Manage your bots and their work."
        case "desk": return "Keep track of tasks on your Desk."
        case "persona": return "Read or update my personality notes."
        case "tool", "list": return "Find and prepare tools for a task."
        case "context", "scratchpad", "recent": return "Look up details from my current work."
        case "contacts": return "Find or update contacts."
        case "messages": return "Read or send messages."
        case "notes": return "Find or write notes."
        case "music": return "See and control what's playing."
        case "voice": return "Turn text into speech."
        case "app", "interaction": return "Read or use controls in this app."
        case "doctor": return "Check the app's health."
        case "workshop": return "Submit work and check its progress."
        case "task": return "Read or share progress on tasks."
        case "studio": return "Explore ideas and keep creative notes."
        case "memory": return "Review moments to remember."
        case "evolution": return "Propose and review app improvements."
        default: return "An additional tool I can use for your tasks."
        }
    }
}
