// PATCH-2026-05-07: ios-sync MacSyncEngine — SnapshotWriter + InboxWatcher (Mac side)
// SnapshotWriter: every N seconds writes app-owned Swift runtime state to iCloud Drive `snapshots/`.
//   Touches KVS key `snapshot_updated` so iOS observes immediately.
// InboxWatcher: NSMetadataQuery on `inbox/`. When iOS drops an action JSON, dispatch to
//   the in-process Swift runtime, write response to `responses/<msg_id>.json`, touch KVS `inbox_response_<msg_id>`.

import CommonCrypto
import CryptoKit
import AppKit
import Foundation
import SwiftUI
import NativeAgentShared
import NativeAgentCore
import KnowledgeGraph
import PersistenceCore

extension MacSyncEngine {
    // C.1: HMAC pairing secret — loaded lazily on first use via PairingSecretManager (single source of truth).
    // TODO(iOS-side): iOS sender must compute HMAC-SHA256 over the canonical
    // JSON body (fields sorted, "signature" key excluded) and include it as
    // the "signature" field in the JSON.  Until then all unsigned messages are
    // rejected when signature validation is enforced.

    private var pairingSecret: Data {
        if let s = _pairingSecret { return s }
        let s = PairingSecretManager.loadOrGenerateSecret()
        _pairingSecret = s
        return s
    }

    /// PATCH-2026-05-08: review-fix-r2 Clear the cached pairing secret so the
    /// next validation reads the freshly-regenerated bytes from disk.
    /// Called by MacPairingView's "Regenerate" action (and by anyone else
    /// who replaces the secret file).
    func invalidatePairingSecret() {
        _pairingSecret = nil
    }

    /// Compute HMAC-SHA256 over `body` using the pairing secret.
    private func hmacSHA256(body: Data) -> String {
        let key = SymmetricKey(data: pairingSecret)
        let mac = HMAC<SHA256>.authenticationCode(for: body, using: key)
        return Data(mac).map { String(format: "%02x", $0) }.joined()
    }

    func signedResponse(_ response: [String: String]) -> [String: String] {
        var body = response
        body.removeValue(forKey: "signature")
        guard let canonical = try? JSONSerialization.data(withJSONObject: body, options: [.sortedKeys]) else {
            return response
        }
        body["signature"] = hmacSHA256(body: canonical)
        return body
    }

    func writeRejectedResponseIfNeeded(action: InboxAction, transactionId: String, message: String) async {
        guard let responsesDir else { return }
        let responseURL = responsesDir.appendingPathComponent("\(action.msgId).json")
        guard !FileManager.default.fileExists(atPath: responseURL.path) else { return }
        let lower = message.lowercased()
        let code: String
        if lower.contains("hmac") || lower.contains("signature wrong") {
            code = "signature_invalid"
        } else if lower.contains("timestamp") || lower.contains("too old") {
            code = "timestamp_invalid"
        } else {
            code = "signature_required"
        }
        let response = signedResponse([
            "status": "error",
            "ok": "false",
            "code": code,
            "message": message,
            "msgId": action.msgId,
            "transactionId": transactionId,
            "action": action.action,
            "createdAt": ISO8601DateFormatter().string(from: Date()),
        ])
        guard let responseData = try? JSONEncoder().encode(response) else { return }
        let msgId = action.msgId
        // Off-main write, but AWAITED so the kvs signal ordering and caller
        // sequencing are preserved (no fire-and-forget race).
        let writeError = await Task.detached(priority: .utility) { [responseURL, responseData] in
            Self.atomicWrite(data: responseData, to: responseURL)
        }.value
        if let writeError {
            syncError = "Could not write rejection response for \(msgId): \(writeError)"
        } else {
            _ = await withCKTimeout("MacSyncEngine.writeRejectedResponse.kvsSignal") {
                let kvs = NSUbiquitousKeyValueStore.default
                kvs.set(msgId, forKey: "inbox_response_\(msgId)")
                return kvs.synchronize()
            }
        }
    }

    /// Write `data` to `url` with atomic semantics. Returns an error description on failure, nil on success.
    /// Must be nonisolated static — called from detached tasks off the main actor.
    nonisolated static func atomicWrite(data: Data, to url: URL) -> String? {
        do {
            try data.write(to: url, options: .atomic)
            return nil
        } catch {
            return error.localizedDescription
        }
    }

    /// N32: Constant-time string comparison to guard against timing attacks.
    /// Returns true iff a == b, without short-circuiting on the first differing byte.
    private func constantTimeEqual(_ a: String, _ b: String) -> Bool {
        let aBytes = Array(a.utf8)
        let bBytes = Array(b.utf8)
        guard aBytes.count == bBytes.count else { return false }
        var diff: UInt8 = 0
        for i in 0..<aBytes.count { diff |= aBytes[i] ^ bBytes[i] }
        return diff == 0
    }

    /// Validate incoming InboxAction:
    ///   1. Timestamp must be within ±5 minutes of now.
    ///   2. HMAC-SHA256 of the canonical body (JSON with keys sorted, signature excluded)
    ///      must match the "signature" field.
    /// Returns nil on success, or an error string to log/reject.
    func validateInboxAction(data: Data, action: InboxAction) async -> String? {
        // 1. Timestamp freshness check.
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let formatter2 = ISO8601DateFormatter() // without fractional seconds fallback
        guard let ts = formatter.date(from: action.createdAt) ?? formatter2.date(from: action.createdAt) else {
            return "invalid timestamp: \(action.createdAt)"
        }
        let age = abs(Date().timeIntervalSince(ts))
        if age > 300 {
            return "message too old: \(Int(age))s"
        }

        // 2. Signature check.
        guard let sig = action.signature else {
            // S.2: write an upgrade-required response so old iOS apps get a clear error
            // instead of timing out waiting for a response that never comes.
            let responseURL = responsesDir?.appendingPathComponent("\(action.msgId).json")
            // fix-R9-3 Use [String: String] so iOS's JSONDecoder([String:String]) can parse it.
            let upgradeResp = signedResponse([
                "msgId":     action.msgId,
                "ok":        "false",
                "error":     "iOS app needs upgrade to enable HMAC signing. Update via App Store / TestFlight.",
                "code":      "signature_required",
                "createdAt": ISO8601DateFormatter().string(from: Date()),
            ])
            // PATCH-2026-05-08: review-fix-r7 Only set KVS after a successful
            // atomic write. Otherwise old iOS gets pinged but finds no
            // response file, and times out anyway.
            var wrote = false
            if let data = try? JSONSerialization.data(withJSONObject: upgradeResp),
               let url = responseURL {
                // crash-class-1: move iCloud write off the MainActor.
                let writeError = await Task.detached(priority: .utility) { [data, url] in
                    Self.atomicWrite(data: data, to: url)
                }.value
                if let writeError {
                    // surface in returned error
                    return "missing signature — failed to write upgrade response: \(writeError)"
                }
                wrote = true
            }
            if wrote {
                let msgId = action.msgId
                _ = await withCKTimeout("MacSyncEngine.validateInboxAction.upgradeResponseKVS") {
                    let kvs = NSUbiquitousKeyValueStore.default
                    kvs.set(msgId, forKey: "inbox_response_\(msgId)")
                    return kvs.synchronize()
                }
            }
            return "missing signature — upgrade response written for iOS client"
        }

        // S.11: reject obviously wrong-format signatures before computing HMAC.
        let hexChars = CharacterSet(charactersIn: "0123456789abcdefABCDEF")
        if sig.count != 64 || sig.unicodeScalars.contains(where: { !hexChars.contains($0) }) {
            return "signature wrong format (expected 64 hex chars, got \(sig.count) chars)"
        }

        // Reconstruct canonical body: re-encode with sorted keys, signature excluded.
        guard let original = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return "cannot re-parse JSON for HMAC"
        }
        var withoutSig = original
        withoutSig.removeValue(forKey: "signature")
        guard let canonical = try? JSONSerialization.data(withJSONObject: withoutSig, options: [.sortedKeys]) else {
            return "cannot re-serialize for HMAC"
        }
        let expected = hmacSHA256(body: canonical)
        // N32: lowercase before compare (hmacSHA256 already produces lowercase hex;
        // guard against iOS sending uppercase) and use constant-time compare.
        let sigLower = sig.lowercased()
        if !constantTimeEqual(sigLower, expected) {
            return "HMAC mismatch — possible tampering or wrong pairing secret"
        }
        return nil // valid
    }
}
