#!/usr/bin/env bash
# script/init_persona.sh — Phase 11: first-run persona initializer.
#
# Called by install_app.sh before launching NativeAgent.app so new
# cloners get working persona docs from the bundled templates. USER.md is
# generated from MemoryV2, not copied from a template.
#
# Behavior (idempotent — safe to re-run):
#   1. If persona/SOUL.md is absent, copy persona/SOUL.template.md → persona/SOUL.md
#   2. If persona/GROWTH.md is absent, copy persona/GROWTH.template.md → persona/GROWTH.md
#   3. Ensure data/ exists (mkdir -p)
#   4. Ensure workspace/ exists (mkdir -p) — Phase 11b
#   5. Print setup summary

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PERSONA_DIR="$ROOT/persona"
DATA_DIR="$ROOT/data"
WORKSPACE_DIR="$ROOT/workspace"

_log() { echo "[init_persona] $*"; }

# N13 fix: use atomic cp (tmp + mv) so an interrupted copy never leaves a
# partial file at the target path.  cp to a tmp name in the same directory,
# then mv atomically replaces the destination.
_atomic_cp() {
    local src="$1" dst="$2"
    local tmp="${dst}.tmp.$$"
    cp "$src" "$tmp" && mv "$tmp" "$dst"
}

# 1. SOUL.md
if [ ! -f "$PERSONA_DIR/SOUL.md" ]; then
    if [ -f "$PERSONA_DIR/SOUL.template.md" ]; then
        _atomic_cp "$PERSONA_DIR/SOUL.template.md" "$PERSONA_DIR/SOUL.md"
        _log "Created persona/SOUL.md from template."
    else
        _log "WARNING: persona/SOUL.template.md not found — skipping SOUL.md creation."
    fi
else
    _log "persona/SOUL.md already exists — skipping."
fi

# 2. USER.md is generated from MemoryV2 into the active persona root. Preserve an
# existing file, but do not create a template copy that can masquerade as memory.
if [ -f "$PERSONA_DIR/USER.md" ]; then
    _log "persona/USER.md already exists — preserving generated memory projection."
else
    _log "persona/USER.md is generated by MemoryV2 — skipping template creation."
fi

# 2b. AGENTS.md (Phase 14: operating manual — personal copy, gitignored)
if [ ! -f "$PERSONA_DIR/AGENTS.md" ]; then
    if [ -f "$PERSONA_DIR/AGENTS.template.md" ]; then
        _atomic_cp "$PERSONA_DIR/AGENTS.template.md" "$PERSONA_DIR/AGENTS.md"
        _log "Created persona/AGENTS.md from template."
    else
        _log "WARNING: persona/AGENTS.template.md not found — skipping AGENTS.md creation."
    fi
else
    _log "persona/AGENTS.md already exists — skipping."
fi

# 2c. GROWTH.md (personal growth journal — template is public, copy is gitignored)
if [ ! -f "$PERSONA_DIR/GROWTH.md" ]; then
    if [ -f "$PERSONA_DIR/GROWTH.template.md" ]; then
        _atomic_cp "$PERSONA_DIR/GROWTH.template.md" "$PERSONA_DIR/GROWTH.md"
        _log "Created persona/GROWTH.md from template."
    else
        _log "WARNING: persona/GROWTH.template.md not found — skipping GROWTH.md creation."
    fi
else
    _log "persona/GROWTH.md already exists — skipping."
fi

# 3. data/ directory
if [ ! -d "$DATA_DIR" ]; then
    mkdir -p "$DATA_DIR"
    _log "Created data/ directory."
else
    _log "data/ already exists — skipping."
fi

# 4. workspace/ directory (Phase 11b)
if [ ! -d "$WORKSPACE_DIR" ]; then
    mkdir -p "$WORKSPACE_DIR"
    touch "$WORKSPACE_DIR/.gitkeep"
    _log "Created workspace/ directory."
else
    _log "workspace/ already exists — skipping."
fi

echo
echo "Setup complete."
echo "  Edit persona/SOUL.md to define your agent's identity."
echo "  persona/USER.md is generated from memory SQLite; save durable user facts through memory."
echo "  Runtime state will be written to data/ (gitignored)."
echo "  Work product (drafts, exports, scratch) goes in workspace/ (gitignored)."
